swagger: "2.0"
info:
  title: The Controversies of Science API
  description: "**The Controversies of Science API is the world's first attempt to systematically document the best critiques of modern science ever published as well as anomalies and former and ongoing scientific controversies.**  The format is a social network card-and-text-based approach designed to service the needs of the layperson public to rapidly understand the gist of some aspect of the scientific controversy topic."
  version: 0.0.1
  contact:
    name: Chris Reeve
    email: paradigmsareconstructed@gmail.com
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /v1
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
securityDefinitions:
  UserSecurity:
    type: basic
  AdminSecurity:
    type: basic
  MediaSecurity:
    type: basic
x-a127-config: {}
x-a127-services: {}
paths:
  /cards:
    # binds a127 app logic to a route
    x-swagger-router-controller: controversy_controller
    x-a127-apply: {}
    get:
      summary: Returns an array of controversy cards, optionally by type query parameter
      description: "Controversy cards cover more than just the controversies themselves.  They may also dedicate to the topic's larger context -- including **against-the-mainstream theorists**, **academic reformers**, **critics** and **whistleblowers**, **online pundits** and **debunkers**, **critical thinking tools**, **academic and science education reform** and **social network design**.  The intention is to break the subject up into discrete units which in total represent a complete taxonomy of this domain."
      # used as the method name of the controller
      operationId: getCardsByType
      tags:
        - Cards
      parameters:
        - name: category
          in: query
          description: "The type of controversy card (ongoing, historical, reform, thinking, critique, person, design)"
          required: false
          type: string
          enum:
            - ongoing
            - historical
            - reform
            - thinking
            - critique
            - person
      responses:
        200:
          description: A list of controversy cards
          schema:
            $ref: "#/definitions/MetaCards"
        404:
          description: There are no cards of that type
        default:
          description: An unexpected error occurred
          schema:
            $ref: "#/definitions/Error"
  /cards/{cardId}:
    x-swagger-router-controller: controversy_controller
    x-a127-apply: {}
    get:
      summary: Gets a specific controversy card by ID
      description: "Controversy cards cover more than just the controversies themselves.  They may also dedicate to the topic's larger context -- including **against-the-mainstream theorists**, **academic reformers**, **critics** and **whistleblowers**, **online pundits** and **debunkers**, **critical thinking tools**, **academic and science education reform** and **social network design**.  The intention is to break the subject up into discrete units which in total represent a complete taxonomy of this domain."
      operationId: getCardById
      tags:
        - Cards
      parameters:
        - name: cardId
          in: path
          description: The controversy card's ID
          required: true
          type: string
      responses:
        200:
          description: Card success
          schema:
            $ref: "#/definitions/ControversyCard"
        404:
          description: The card does not exist
          schema:
            $ref: "#/definitions/Error"
        default:
          description: An unexpected error occurred
          schema:
            $ref: "#/definitions/Error"
  /sync:
    x-swagger-router-controller: controversy_controller
    x-a127-apply: {}
    get:
      summary: Synchronizes backend collection to Controversies of Science Google Plus collection 
      description: "Scraper script"
      operationId: syncCollection
      responses:
        200:
          description: Scrape success
          schema:
            $ref: "#/definitions/CardTitleList"
        404:
          description: Scrape failed
          schema:
            $ref: "#/definitions/Error"
        default:
          description: An unexpected scrape error occurred
          schema:
            $ref: "#/definitions/Error"
definitions:
  CardTitleList:
    type: array
    items:
      type: string
  User:
    required:
      - userId
      - email
    properties:
      userId:
        type: integer
        minimum: 0
        exclusiveMinimum: false
      username:
        type: string
      avatar:
        type: string
      email:
        type: string
      bio:
        type: string
      lastTimeOnline:
        type: string
        format: date-time
  MetaCard:
    title: Metacard
    description: Metadata associated with a controversy card
    required:
      - url
      - name
    properties:
      name:
        type: string
      summary:
        type: string
      author:
        $ref: "#/definitions/User"
      url:
        type: string
      thumbnail:
        type: string
      publishDate:
        type: string
        format: date-time
      updateDate:
        type: string
        format: date-time
      category:
        type: string
  MetaCards:
    type: array
    items:
      $ref: "#/definitions/MetaCard"
  Footnote:
    title: Reference
    description: Source or footnote for a controversy card
    properties:
      selector:
        type: string
      markup:
        type: string
  Footnotes:
    type: array
    items:
      $ref: "#/definitions/Footnote"
  Annotation:
    title: Annotation
    description: A discussion about some portion of controversy card
    required:
      - userId
    properties:
      userId:
        type: integer
        minimum: 0
        exclusiveMinimum: false        
      userThumbnail:
        type: string
      annotationThumbnail:
        type: string
      annotationFormat:
        type: string
      annotationUrl:
        type: string
      annotationTitle:
        type: string
      attachWhere:
        type: string
  Annotations:
    type: array
    items:
      $ref: "#/definitions/Annotation"
  Slide:
    title: Impress.js Slide
    description: A slideshow frame to zoom to
    properties:
      selector:
        type: string
      x:
        type: integer
      y:
        type: integer
      scale:
        type: number
  Slides:
    type: array
    items:
      $ref: "#/definitions/Slide"
  ControversyCard:
    properties:
      metaCard:
        $ref: "#/definitions/MetaCard"
      markup:
        type: string
      slides:
        $ref: "#/definitions/Slides"
      footnotes:
        $ref: "#/definitions/Footnotes"
      textAnnotations:
        $ref: "#/definitions/Annotations"
      graphicAnnotations:
        $ref: "#/definitions/Annotations"
      prerequisiteCards:
        $ref: "#/definitions/MetaCards"
      relatedCards:
        $ref: "#/definitions/MetaCards"
  Error:
    properties:
      code:
        type: string
      message:
        type: string
